# Generated by Django 5.2.5 on 2025-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='runs_on',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', max_length=3),
        ),
    ]
