# Generated by Django 5.2.5 on 2025-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_classificationmodel_runs_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='classes',
            field=models.TextField(blank=True),
        ),
    ]
