# Generated by Django 5.2.5 on 2025-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_classificationmodel_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationmodel',
            name='classes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classificationmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
