# Generated by Django 5.2.5 on 2025-08-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_alter_classificationmodel_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.CharField(max_length=512)),
                ('results_summary', models.CharField(max_length=512)),
                ('classification_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='classifier.classificationmodel')),
            ],
        ),
    ]
